### ISSUE TITLE
www.movim.eu shows API

### ISSUE THREAD

**Issue by MarcelWaldvogel** [movim/movim_home#8]
http://www.movim.eu (HTTP, no S) redirects to https://api.movim.eu, while https://www.movim.eu (HTTPS, with S) directly shows the same content as https://api.movim.eu

Unless there is a technical reason for this behaviour, it would be more user-friendly to have both redirect to https://movim.eu

**Comment by debdolph** [comment]
Now https://www.movim.eu/ and http://www.movim.eu/ shows https://edhelas.movim.eu/

**Comment by edhelas** [comment]
This has been fixed. Thanks.
